# Generated by Django 4.1.7 on 2023-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='requirement',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_active',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_tenure',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
