# Generated by Django 4.1.7 on 2023-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_requirement_lead_service_active_lead_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
