# Generated by Django 4.2 on 2023-04-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadd_leadaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('lead_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='leadaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.upcoming_lead'),
        ),
        migrations.DeleteModel(
            name='Leadd',
        ),
    ]
